/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GatePassRouteImport } from './routes/gate-pass'
import { Route as IndexRouteImport } from './routes/index'

const GatePassRoute = GatePassRouteImport.update({
  id: '/gate-pass',
  path: '/gate-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gate-pass': typeof GatePassRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gate-pass': typeof GatePassRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gate-pass': typeof GatePassRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gate-pass'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gate-pass'
  id: '__root__' | '/' | '/gate-pass'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GatePassRoute: typeof GatePassRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gate-pass': {
      id: '/gate-pass'
      path: '/gate-pass'
      fullPath: '/gate-pass'
      preLoaderRoute: typeof GatePassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GatePassRoute: GatePassRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
