/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockConsolidationRouteImport } from './routes/stock-consolidation'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as MeasurementBookRouteImport } from './routes/measurement-book'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GatePassRouteImport } from './routes/gate-pass'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const StockConsolidationRoute = StockConsolidationRouteImport.update({
  id: '/stock-consolidation',
  path: '/stock-consolidation',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementBookRoute = MeasurementBookRouteImport.update({
  id: '/measurement-book',
  path: '/measurement-book',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GatePassRoute = GatePassRouteImport.update({
  id: '/gate-pass',
  path: '/gate-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gate-pass': typeof GatePassRoute
  '/login': typeof LoginRoute
  '/measurement-book': typeof MeasurementBookRoute
  '/returns': typeof ReturnsRoute
  '/stock-consolidation': typeof StockConsolidationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gate-pass': typeof GatePassRoute
  '/login': typeof LoginRoute
  '/measurement-book': typeof MeasurementBookRoute
  '/returns': typeof ReturnsRoute
  '/stock-consolidation': typeof StockConsolidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gate-pass': typeof GatePassRoute
  '/login': typeof LoginRoute
  '/measurement-book': typeof MeasurementBookRoute
  '/returns': typeof ReturnsRoute
  '/stock-consolidation': typeof StockConsolidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/gate-pass'
    | '/login'
    | '/measurement-book'
    | '/returns'
    | '/stock-consolidation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/gate-pass'
    | '/login'
    | '/measurement-book'
    | '/returns'
    | '/stock-consolidation'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/gate-pass'
    | '/login'
    | '/measurement-book'
    | '/returns'
    | '/stock-consolidation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GatePassRoute: typeof GatePassRoute
  LoginRoute: typeof LoginRoute
  MeasurementBookRoute: typeof MeasurementBookRoute
  ReturnsRoute: typeof ReturnsRoute
  StockConsolidationRoute: typeof StockConsolidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock-consolidation': {
      id: '/stock-consolidation'
      path: '/stock-consolidation'
      fullPath: '/stock-consolidation'
      preLoaderRoute: typeof StockConsolidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurement-book': {
      id: '/measurement-book'
      path: '/measurement-book'
      fullPath: '/measurement-book'
      preLoaderRoute: typeof MeasurementBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate-pass': {
      id: '/gate-pass'
      path: '/gate-pass'
      fullPath: '/gate-pass'
      preLoaderRoute: typeof GatePassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GatePassRoute: GatePassRoute,
  LoginRoute: LoginRoute,
  MeasurementBookRoute: MeasurementBookRoute,
  ReturnsRoute: ReturnsRoute,
  StockConsolidationRoute: StockConsolidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
